### ISSUE TITLE
PVox broke certain addon

### ISSUE THREAD

**Issue by amneyxa** [kdgonz7/ImmPVox#15]
This specific addon, "[[VManip] Manual Pickup](https://steamcommunity.com/sharedfiles/filedetails/?id=2156004721)" seemed to stop working with this addon instead. I'm not sure what causes the issue since theres no errors being made in the console, but it auto-picks up weapons with PVox installed.

**Comment by kdgonz7** [comment]
Thanks for reporting this. I'm 100% assuming it has something to do with the Pickup hook that PVox overrides. I will work on a fix ASAP.

**Comment by kdgonz7** [comment]
https://github.com/kdgonz7/ImmPVox/blob/4e2f10f166c3c4692dae1ff3837b8951d9f97492/lua/autorun/playervox.lua#L1022-L1034

Most likely where problematic issue arises from.

**Comment by amneyxa** [comment]
Will this fix before next update?

**Comment by kdgonz7** [comment]
@amneyxa yes, once i figure out how when i get time
