### ISSUE TITLE
implement a Left 4 Dead styled reload callout

### ISSUE THREAD

**Issue by MannMakerStudio17** [kdgonz7/ImmPVox#4]
i'm getting tired the player will shout "Reload", every time when they reload the gun

why you can use the reload callout system like in Left 4 Dead

they have 1 in 5 chance of the player will shout "Reload" while reloading

**Comment by kdgonz7** [comment]
I will either implement that as a separate module or as a cvar. A feature like that would be nice for people who are looking for that sort of system, however for the people that are fine with the existing system will find a change like that hardcoded a bit annoying, so I'll work on making sure that you can do something like that in v9
