### ISSUE TITLE
my new features/modules suggestions for v9 update

### ISSUE THREAD

**Issue by MannMakerStudio17** [kdgonz7/ImmPVox#5]
here's some new goodies for the upcoming v9 update of pvox

- support for uwu's [Glory Kills](https://steamcommunity.com/sharedfiles/filedetails/?id=2301721246&tscn=1606584895) and RandomPerson189's [BSMod Killmove](https://steamcommunity.com/workshop/filedetails/?id=2106330193) (triggers a callout after doing a killmove)
- support for Zet0r's [NZombies](https://github.com/Zet0rz/nzombies/tree/master-workshop) (triggers a callout, everytime when using perk-a-cola, pack-a-puch, mystery box, open a debris, etc)
- playermodel specific footstep sound
- falling scream
- jump sound (1 in 7 chance the callout will play)
- low health (1 in 5 chance the callout will play, like Left 4 Dead survivors)
- melee swing (1 in 7 chance the callout will play)
- breathing when sprinting for a long time (1 in 5 chance the callout will play)
- an option to change keybinds for "inspect" callout
- an option to change footstep sound preset into another playermodel

you think this will take hours right ? well, you can think about it.

**Comment by kdgonz7** [comment]
## Roadmap

| Feature                                           | Status?           | Possible? | Reason                                                                                                                                                                                                  |
|---------------------------------------------------|-------------------|-----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Support for Glory Kills                           | 🛠                 | ✅         | N/A                                                                                                                                                                                                     |
| Support for BSMod Killmoves                       | ❓                 | ✅         | Question mark, unknown API at this moment.                                                                                                                                                              |
| Support for NZombies                              | 🛠                 | ✅         | N/A, creator has a TFA-VOX module built-in.                                                                                                                                                             |
| Playermodel-based footsteps                       | ❓                 | ✅         | It can easily be implemented, but may not be compatible with specific footstep mods, may be clutter.                                                                                                    |
| Falling VOX                                       | ❓                 | ❓         | I have not figured out how to calculate if the player is falling efficiently. Will keep on radar @ lower pri.                                                                                           |
| Low Health VOX                                    | ❌                 | ❔         | Request very vague, unknown goal. Don't know what "Low health" is meant to specify. When the players health changes to a low amount? Or when the player IS AT low health and are just passive callouts? |
| Melee Swing VOX                                   | 🔄                 | ✅         | May be inconvenient to implement on every swing. Will be implementing on MELEE KILLS, but not swings unless further information and examples provided.                                                  |
| Breathing While Sprinting VOX                     | 🔄                 | ✅         | May be inconvenient, as, again, it will have to be checked on every couple frames to ensure no sprint is missed.                                                                                        |
| An option to change the "PVOX Inspect Module" key | ✅ (Will be in v9) | ✅         | Good suggestion, will be implemented.                                                                                                                                                                   |

**Comment by kdgonz7** [comment]
Closing this, as I have created separate issues for this case. Extended actions will be in a separate branch. Sort by newest issues.
